CREATE DATABASE  IF NOT EXISTS `rba-innophyt` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `rba-innophyt`;

CREATE TABLE TABLE_USER (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	NOM VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	PASSWD TEXT NOT NULL,
	RSA_PRIVE TEXT,
	IP_LB TEXT,
	IP_UB TEXT,
	UNIQUE (NOM, EMAIL));

CREATE TABLE TABLE_CAMPAGNE (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	UTILISATEUR_ID INTEGER NOT NULL,
	NOM VARCHAR(50) NOT NULL,
	DATE_DEBUT DATE,
	DATE_FIN DATE,
	ADRESSE VARCHAR(250),
	LATITUDE VARCHAR(25),
	LONGITUDE VARCHAR(25),
	DESCRIPTION VARCHAR(1024),
	FOREIGN KEY(UTILISATEUR_ID) REFERENCES TABLE_USER(ID) ON DELETE CASCADE,
	UNIQUE (UTILISATEUR_ID,NOM));
	
CREATE TABLE TABLE_PARCELLE (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	CAMPAGNE_ID INTEGER NOT NULL,
	NOM VARCHAR(50) NOT NULL,
	DATE_DEBUT DATE,
	DATE_FIN DATE,
	ADRESSE VARCHAR(250),
	LATITUDE VARCHAR(25),
	LONGITUDE VARCHAR(25),
	DESCRIPTION VARCHAR(1024),
	FOREIGN KEY(CAMPAGNE_ID) REFERENCES TABLE_CAMPAGNE(ID) ON DELETE CASCADE,
	UNIQUE (CAMPAGNE_ID,NOM));
	
CREATE TABLE TABLE_PIEGE (
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	PARCEL_ID INTEGER NOT NULL,
	NOM VARCHAR(50) NOT NULL,
	DATE_DEBUT DATE,
	DATE_FIN DATE,
	ADRESSE VARCHAR(250),
	LATITUDE VARCHAR(25),
	LONGITUDE VARCHAR(25),
	DESCRIPTION VARCHAR(1024),
	FOREIGN KEY(PARCEL_ID) REFERENCES TABLE_PARCELLE(ID) ON DELETE CASCADE,
	UNIQUE (PARCEL_ID,NOM,DATE_FIN));
	
CREATE TABLE TABLE_RECOLTE(
	ID INTEGER PRIMARY KEY AUTO_INCREMENT,
	PIEGE_ID INTEGER NOT NULL,
	NOM VARCHAR(50) NOT NULL,
	TYPE_INSECTE VARCHAR(250),
	REGIME_INSECTE VARCHAR(512),
	INFOS_INSECTE VARCHAR(1024),
	TYPE_ID_INSECTE VARCHAR(50),
	DEBUT_ID_INSECTE DATETIME,
	FIN_ID_INSECTE DATETIME,
	NOMBRE INTEGER,
	DATE DATE,
	ID_UTILISATEUR INTEGER NOT NULL,
	FOREIGN KEY(PIEGE_ID) REFERENCES TABLE_PIEGE(ID) ON DELETE CASCADE,
	UNIQUE (PIEGE_ID,NOM,ID_UTILISATEUR));
	
CREATE TABLE android_metadata (locale TEXT);
