SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP SCHEMA IF EXISTS `rba-innophyt` ;
CREATE SCHEMA IF NOT EXISTS `rba-innophyt` DEFAULT CHARACTER SET utf8 ;
USE `rba-innophyt` ;

-- -----------------------------------------------------
-- Table `rba-innophyt`.`TABLE_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rba-innophyt`.`TABLE_USER` ;

CREATE  TABLE IF NOT EXISTS `rba-innophyt`.`TABLE_USER` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `NOM` VARCHAR(30) NOT NULL ,
  `ADMIN` TINYINT(1) NOT NULL DEFAULT FALSE ,
  `EMAIL` VARCHAR(30) NOT NULL ,
  `PASSWD` TEXT NOT NULL ,
  `TOKEN` TEXT NULL ,
  `IP_LB` TEXT NULL DEFAULT NULL ,
  `IP_UB` TEXT NULL DEFAULT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `NOM` (`NOM` ASC, `EMAIL` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rba-innophyt`.`TABLE_CAMPAGNE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rba-innophyt`.`TABLE_CAMPAGNE` ;

CREATE  TABLE IF NOT EXISTS `rba-innophyt`.`TABLE_CAMPAGNE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `UTILISATEUR_ID` INT(11) NOT NULL ,
  `NOM` VARCHAR(250) NOT NULL ,
  `DATE_DEBUT` DATE NULL DEFAULT NULL ,
  `DATE_FIN` DATE NULL DEFAULT NULL ,
  `ADRESSE` VARCHAR(250) NULL DEFAULT NULL ,
  `LATITUDE` VARCHAR(25) NULL DEFAULT NULL ,
  `LONGITUDE` VARCHAR(25) NULL DEFAULT NULL ,
  `DESCRIPTION` VARCHAR(1024) NULL DEFAULT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `UTILISATEUR_ID` (`UTILISATEUR_ID` ASC, `NOM` ASC) ,
  CONSTRAINT `TABLE_CAMPAGNE_ibfk_1`
    FOREIGN KEY (`UTILISATEUR_ID` )
    REFERENCES `rba-innophyt`.`TABLE_USER` (`ID` )
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rba-innophyt`.`TABLE_PARCELLE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rba-innophyt`.`TABLE_PARCELLE` ;

CREATE  TABLE IF NOT EXISTS `rba-innophyt`.`TABLE_PARCELLE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `CAMPAGNE_ID` INT(11) NOT NULL ,
  `NOM` VARCHAR(250) NOT NULL ,
  `DATE_DEBUT` DATE NULL DEFAULT NULL ,
  `DATE_FIN` DATE NULL DEFAULT NULL ,
  `ADRESSE` VARCHAR(250) NULL DEFAULT NULL ,
  `LATITUDE` VARCHAR(25) NULL DEFAULT NULL ,
  `LONGITUDE` VARCHAR(25) NULL DEFAULT NULL ,
  `DESCRIPTION` VARCHAR(1024) NULL DEFAULT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `CAMPAGNE_ID` (`CAMPAGNE_ID` ASC, `NOM` ASC) ,
  CONSTRAINT `TABLE_PARCELLE_ibfk_1`
    FOREIGN KEY (`CAMPAGNE_ID` )
    REFERENCES `rba-innophyt`.`TABLE_CAMPAGNE` (`ID` )
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rba-innophyt`.`TABLE_PIEGE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rba-innophyt`.`TABLE_PIEGE` ;

CREATE  TABLE IF NOT EXISTS `rba-innophyt`.`TABLE_PIEGE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `PARCEL_ID` INT(11) NOT NULL ,
  `NOM` VARCHAR(250) NOT NULL ,
  `DATE_DEBUT` DATE NULL DEFAULT NULL ,
  `DATE_FIN` DATE NULL DEFAULT NULL ,
  `ADRESSE` VARCHAR(250) NULL DEFAULT NULL ,
  `LATITUDE` VARCHAR(25) NULL DEFAULT NULL ,
  `LONGITUDE` VARCHAR(25) NULL DEFAULT NULL ,
  `DESCRIPTION` VARCHAR(1024) NULL DEFAULT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `PARCEL_ID` (`PARCEL_ID` ASC, `NOM` ASC, `DATE_FIN` ASC) ,
  CONSTRAINT `TABLE_PIEGE_ibfk_1`
    FOREIGN KEY (`PARCEL_ID` )
    REFERENCES `rba-innophyt`.`TABLE_PARCELLE` (`ID` )
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rba-innophyt`.`TABLE_RECOLTE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rba-innophyt`.`TABLE_RECOLTE` ;

CREATE  TABLE IF NOT EXISTS `rba-innophyt`.`TABLE_RECOLTE` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT ,
  `PIEGE_ID` INT(11) NOT NULL ,
  `NOM` VARCHAR(250) NOT NULL ,
  `TYPE_INSECTE` VARCHAR(250) NULL DEFAULT NULL ,
  `REGIME_INSECTE` VARCHAR(512) NULL DEFAULT NULL ,
  `INFOS_INSECTE` VARCHAR(1024) NULL DEFAULT NULL ,
  `TYPE_ID_INSECTE` VARCHAR(50) NULL DEFAULT NULL ,
  `DEBUT_ID_INSECTE` DATETIME NULL DEFAULT NULL ,
  `FIN_ID_INSECTE` DATETIME NULL DEFAULT NULL ,
  `NOMBRE` INT(11) NULL DEFAULT NULL ,
  `DATE` DATE NULL DEFAULT NULL ,
  `ID_UTILISATEUR` INT(11) NOT NULL ,
  PRIMARY KEY (`ID`) ,
  UNIQUE INDEX `PIEGE_ID` (`PIEGE_ID` ASC, `NOM` ASC, `ID_UTILISATEUR` ASC) ,
  CONSTRAINT `TABLE_RECOLTE_ibfk_1`
    FOREIGN KEY (`PIEGE_ID` )
    REFERENCES `rba-innophyt`.`TABLE_PIEGE` (`ID` )
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `rba-innophyt`.`android_metadata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rba-innophyt`.`android_metadata` ;

CREATE  TABLE IF NOT EXISTS `rba-innophyt`.`android_metadata` (
  `locale` TEXT NULL DEFAULT NULL )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `rba-innophyt` ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
